version: '3.8'

services:
  web:
    build: .
    restart: unless-stopped
    network_mode: "host"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5433/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_APP=run.py
      - FLASK_ENV=production
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./instance:/app/instance

  db:
    image: postgres:14
    restart: unless-stopped
    network_mode: "host"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPORT=5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p 5433"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
